# Generated by Django 5.0.7 on 2025-11-16 17:08

from django.db import migrations
from decimal import Decimal


def populate_initial_data(apps, schema_editor):
    """
    Populates the database with initial menu items, recipes, and related data.
    """
    # Get models from the app registry
    Branch = apps.get_model("inventory", "Branch")
    MenuCategory = apps.get_model("inventory", "MenuCategory")
    RawMaterial = apps.get_model("inventory", "RawMaterial")
    Recipe = apps.get_model("inventory", "Recipe")
    RecipeItem = apps.get_model("inventory", "RecipeItem")
    MenuItem = apps.get_model("inventory", "MenuItem")
    MenuItemBranchAvailability = apps.get_model(
        "inventory", "MenuItemBranchAvailability"
    )

    # --- 1. Create Branches ---
    addu_branch, _ = Branch.objects.get_or_create(name="AdDU")
    toril_branch, _ = Branch.objects.get_or_create(name="Toril")
    all_branches = [addu_branch, toril_branch]

    # --- 2. Create Menu Categories ---
    combo_cat, _ = MenuCategory.objects.get_or_create(name="Combo")
    dish_cat, _ = MenuCategory.objects.get_or_create(name="Dish")
    side_cat, _ = MenuCategory.objects.get_or_create(name="Side")

    # --- 3. Create Raw Materials ---
    # Using get_or_create to avoid duplicates if migration is run more than once.
    # Prices and thresholds are illustrative.
    raw_materials = {
        "Chicken": {"unit": "kg", "type": "raw"},
        "Pork": {"unit": "kg", "type": "raw"},
        "Tuna": {"unit": "kg", "type": "raw"},
        "Eggs": {"unit": "pcs", "type": "raw"},
        "Onion": {"unit": "kg", "type": "raw"},
        "Lemon": {"unit": "pcs", "type": "raw"},
        "Rice": {"unit": "kg", "type": "raw"},
        "Mayo": {"unit": "g", "type": "processed"},
        "Oil": {"unit": "ml", "type": "processed"},
        "Salt": {"unit": "g", "type": "processed"},
        "Soy Sauce": {"unit": "ml", "type": "processed"},
        "Coke (250 ml)": {"unit": "pcs", "type": "processed"},
    }

    created_materials = {}
    for name, details in raw_materials.items():
        material, _ = RawMaterial.objects.get_or_create(
            name=name,
            defaults={
                "unit": details["unit"],
                "material_type": details["type"],
                "minimum_threshold": Decimal("1.000"),
                "reorder_level": Decimal("2.000"),
            },
        )
        created_materials[name] = material

    # --- 4. Create Recipes and Recipe Items ---

    # Helper to create recipes
    def create_recipe(name, ingredients, yield_qty=1, yield_uom="serving"):
        recipe, _ = Recipe.objects.get_or_create(
            name=name,
            defaults={"yield_quantity": Decimal(yield_qty), "yield_uom": yield_uom},
        )
        for material_name, quantity in ingredients.items():
            RecipeItem.objects.get_or_create(
                recipe=recipe,
                raw_material=created_materials[material_name],
                defaults={"quantity": Decimal(quantity)},
            )
        return recipe

    # Sisig base ingredients (quantities are for one serving)
    sisig_base = {
        "Onion": "0.050",  # 50g
        "Lemon": "0.5",  # Half a lemon
        "Soy Sauce": "0.015",  # 15ml
        "Oil": "0.010",  # 10ml
        "Mayo": "0.030",  # 30g
        "Salt": "0.002",  # 2g
        "Eggs": "1",
    }

    # Create individual recipes
    chicken_sisig_recipe = create_recipe(
        "Chicken Sisig Recipe", {"Chicken": "0.150", **sisig_base}
    )
    pork_sisig_recipe = create_recipe(
        "Pork Sisig Recipe", {"Pork": "0.150", **sisig_base}
    )
    tuna_sisig_recipe = create_recipe(
        "Tuna Sisig Recipe", {"Tuna": "0.150", **sisig_base}
    )
    egg_sisig_recipe = create_recipe(
        "Egg Sisig Recipe", {"Eggs": "2", **{k: v for k, v in sisig_base.items() if k != 'Eggs'}}
    )
    extra_rice_recipe = create_recipe(
        "Extra Rice Recipe", {"Rice": "0.100"}, yield_uom="serving"
    )
    coke_recipe = create_recipe(
        "Coke Recipe", {"Coke (250 ml)": "1"}, yield_uom="serving"
    )

    # Combo recipe
    pork_sisig_combo_recipe = create_recipe(
        "Pork Sisig with Rice and Coke Recipe",
        {
            "Pork": "0.150",
            **sisig_base,
            "Rice": "0.100",
            "Coke (250 ml)": "1",
        },
    )

    # --- 5. Create Menu Items ---
    menu_items_to_create = [
        {
            "name": "Chicken Sisig",
            "category": dish_cat,
            "recipe": chicken_sisig_recipe,
            "price": "150.00",
        },
        {
            "name": "Pork Sisig",
            "category": dish_cat,
            "recipe": pork_sisig_recipe,
            "price": "150.00",
        },
        {
            "name": "Tuna Sisig",
            "category": dish_cat,
            "recipe": tuna_sisig_recipe,
            "price": "140.00",
        },
        {
            "name": "Egg Sisig",
            "category": dish_cat,
            "recipe": egg_sisig_recipe,
            "price": "120.00",
        },
        {
            "name": "Pork Sisig with Rice and Coke",
            "category": combo_cat,
            "recipe": pork_sisig_combo_recipe,
            "price": "199.00",
        },
        {
            "name": "Extra Rice",
            "category": side_cat,
            "recipe": extra_rice_recipe,
            "price": "25.00",
        },
        {
            "name": "Coke",
            "category": side_cat,
            "recipe": coke_recipe,
            "price": "30.00",
        },
    ]

    for item_data in menu_items_to_create:
        menu_item, _ = MenuItem.objects.get_or_create(
            name=item_data["name"],
            defaults={
                "category": item_data["category"],
                "recipe": item_data["recipe"],
                "description": f"Delicious {item_data['name']}",
            },
        )

        # --- 6. Set Branch Availability and Pricing ---
        is_combo = item_data["name"] == "Pork Sisig with Rice and Coke"

        for branch in all_branches:
            is_active = True
            # Special rule: Pork Sisig combo is not available in AdDU
            if is_combo and branch.name == "AdDU":
                is_active = False

            MenuItemBranchAvailability.objects.get_or_create(
                menu_item=menu_item,
                branch=branch,
                defaults={
                    "price": Decimal(item_data["price"]),
                    "is_active": is_active,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"), # Assuming your first migration is 0001_initial
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]