# Generated by Django 5.2.5 on 2025-09-16 04:15

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator


def create_default_units(apps, schema_editor):
    UnitOfMeasurement = apps.get_model('inventory', 'UnitOfMeasurement')
    
    # Create default units
    default_units = [
        {'name': 'Kilograms', 'abbreviation': 'kg'},
        {'name': 'Grams', 'abbreviation': 'g'},
        {'name': 'Liters', 'abbreviation': 'l'},
        {'name': 'Milliliters', 'abbreviation': 'ml'},
        {'name': 'Pieces', 'abbreviation': 'pcs'},
    ]
    
    for unit_data in default_units:
        UnitOfMeasurement.objects.get_or_create(
            abbreviation=unit_data['abbreviation'],
            defaults=unit_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(0)])),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_units),
    ]
