# Generated by Django 5.2.4 on 2025-09-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250916_1215'),
        ('inventory', '0002_menucategory_recipe_remove_rawmaterial_quantity_and_more'),
    ]

    operations = [
    ]
