# Generated by Django 5.2.4 on 2025-09-17 16:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_merge_20250917_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Current stock quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
