# Generated by Django 5.2.5 on 2025-09-18 14:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_rawmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_rawmaterial_name_ci'),
        ),
    ]
