# Generated by Django 4.2.23 on 2025-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rawmaterial_uniq_rawmaterial_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
