# Generated by Django 5.2.5 on 2025-09-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorder_encoded_by_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='encoded_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who encoded this purchase order', max_length=150, null=True),
        ),
    ]
