# Generated by Django 5.2.5 on 2025-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorder_encoded_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='performed_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who performed this transaction', max_length=150, null=True),
        ),
    ]
