# Generated by Django 5.2.4 on 2025-09-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_menuitem_available_from_menuitem_available_to'),
        ('inventory', '0008_stocktransaction_performed_by_name'),
    ]

    operations = [
    ]
