# Generated by Django 5.2.4 on 2025-09-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_merge_20250921_2142'),
        ('inventory', '0009_merge_20250921_2214'),
    ]

    operations = [
    ]
