# Generated by Django 5.2.5 on 2025-10-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_customerorder_orderitem_and_more'),
    ]

    operations = [
    ]
