# Generated by Django 5.2.5 on 2025-10-15 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20251012_2031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiration date of the material', null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=3, default=10, help_text='Minimum quantity before low stock alert', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=20, help_text='Quantity level to trigger reorder', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('reorder', 'Reorder Level')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('message', models.TextField()),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
