# Generated by Django 5.2.5 on 2025-10-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rawmaterial_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiration date of this item', null=True),
        ),
    ]
