# Generated by Django 5.2.5 on 2025-10-15 09:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_purchaseorderitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days this material stays fresh after purchase'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity in this batch', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('purchase_date', models.DateField(help_text='Date this batch was purchased')),
                ('expiry_date', models.DateField(help_text='Date this batch expires')),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='inventory.purchaseorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['expiry_date'],
            },
        ),
    ]
