# Generated by Django 5.2.5 on 2025-10-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_rawmaterial_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_type',
            field=models.CharField(default='raw', help_text='Type of material for new materials', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=7, help_text='Shelf life in days for this specific purchase batch'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('processed', 'Processed Good'), ('semi_processed', 'Semi-Processed')], default='raw', help_text='Type of material - raw, processed, or semi-processed', max_length=20),
        ),
    ]
