# Generated by Django 5.2.5 on 2025-10-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseorderitem_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('processed', 'Processed Good'), ('semi_processed', 'Semi-Processed'), ('supplies', 'Supplies & Utensils')], default='raw', help_text='Type of material - raw, processed, semi-processed, or supplies', max_length=20),
        ),
    ]
