# Generated by Django 5.2.5 on 2025-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_rawmaterial_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this material stays fresh after purchase. Leave empty for non-perishable items.', null=True),
        ),
    ]
