# Generated by Django 5.2.5 on 2025-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_rawmaterial_shelf_life_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Shelf life in days for this specific purchase batch', null=True),
        ),
    ]
