# Generated by Django 5.2.4 on 2025-10-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='valid_until',
        ),
        migrations.CreateModel(
            name='MenuItemBranchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_availability', to='inventory.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availability', to='inventory.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Branch Availability',
                'verbose_name_plural': 'Menu Item Branch Availabilities',
                'unique_together': {('menu_item', 'branch')},
            },
        ),
    ]
