# Generated by Django 5.2.5 on 2025-10-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this order was placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.branch'),
        ),
    ]
