# Generated by Django 5.2.4 on 2025-10-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_customerorder_branch'),
        ('inventory', '0021_remove_menuitem_available_from_and_more'),
    ]

    operations = [
    ]
