# Generated by Django 5.2.4 on 2025-10-16 16:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_merge_20251016_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitembranchavailability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Price of the menu item at this specific branch.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
