# Generated by Django 5.2.5 on 2025-10-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_branch_based_inventory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchquantity',
            name='unique_branch_rawmaterial',
        ),
        migrations.AlterUniqueTogether(
            name='branchquantity',
            unique_together={('branch', 'raw_material')},
        ),
    ]
