# Generated by Django 5.2.5 on 2025-11-02 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_stockalert_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this transaction occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.branch'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_s_branch__3e0caa_idx'),
        ),
    ]
