# Generated by Django 5.2.4 on 2025-11-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_populate_menu_data'),
        ('inventory', '0027_stocktransaction_branch_and_more'),
    ]

    operations = [
    ]
